countryCodes = {
    "afghanistan": "AFG",
    "Ã…land islands": "ALA",
    "albania": "ALB",
    "algeria": "DZA",
    "american samoa": "ASM",
    "andorra": "AND",
    "angola": "AGO",
    "anguilla": "AIA",
    "antarctica": "ATA",
    "antigua and barbuda": "ATG",
    "argentina": "ARG",
    "armenia": "ARM",
    "aruba": "ABW",
    "australia": "AUS",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahamas": "BHS",
    "bahrain": "BHR",
    "bangladesh": "BGD",
    "barbados": "BRB",
    "belarus": "BLR",
    "belgium": "BEL",
    "belize": "BLZ",
    "benin": "BEN",
    "bermuda": "BMU",
    "bhutan": "BTN",
    "bolivia (plurinational state of)": "BOL",
    "bonaire, sint eustatius and saba": "BES",
    "bosnia and herzegovina": "BIH",
    "botswana": "BWA",
    "bouvet island": "BVT",
    "brazil": "BRA",
    "british indian ocean territory": "IOT",
    "brunei darussalam": "BRN",
    "bulgaria": "BGR",
    "burkina faso": "BFA",
    "burundi": "BDI",
    "cambodia": "KHM",
    "cameroon": "CMR",
    "canada": "CAN",
    "cabo verde": "CPV",
    "cayman islands": "CYM",
    "central african republic": "CAF",
    "chad": "TCD",
    "chile": "CHL",
    "china": "CHN",
    "christmas island": "CXR",
    "cocos (keeling) islands": "CCK",
    "colombia": "COL",
    "comoros": "COM",
    "congo": "COG",
    "congo (democratic republic of the)": "COD",
    "cook islands": "COK",
    "costa rica": "CRI",
    "cÃ´te d'ivoire": "CIV",
    "croatia": "HRV",
    "cuba": "CUB",
    "curaÃ§ao": "CUW",
    "cyprus": "CYP",
    "czech republic": "CZE",
    "denmark": "DNK",
    "djibouti": "DJI",
    "dominica": "DMA",
    "dominican republic": "DOM",
    "ecuador": "ECU",
    "egypt": "EGY",
    "el salvador": "SLV",
    "equatorial guinea": "GNQ",
    "eritrea": "ERI",
    "estonia": "EST",
    "ethiopia": "ETH",
    "falkland islands (malvinas)": "FLK",
    "faroe islands": "FRO",
    "fiji": "FJI",
    "finland": "FIN",
    "france": "FRA",
    "french guiana": "GUF",
    "french polynesia": "PYF",
    "french southern territories": "ATF",
    "gabon": "GAB",
    "gambia": "GMB",
    "georgia": "GEO",
    "germany": "DEU",
    "ghana": "GHA",
    "gibraltar": "GIB",
    "greece": "GRC",
    "greenland": "GRL",
    "grenada": "GRD",
    "guadeloupe": "GLP",
    "guam": "GUM",
    "guatemala": "GTM",
    "guernsey": "GGY",
    "guinea": "GIN",
    "guinea-bissau": "GNB",
    "guyana": "GUY",
    "haiti": "HTI",
    "heard island and mcdonald islands": "HMD",
    "holy see": "VAT",
    "honduras": "HND",
    "hungary": "HUN",
    "iceland": "ISL",
    "india": "IND",
    "indonesia": "IDN",
    "iran (islamic republic of)": "IRN",
    "iraq": "IRQ",
    "ireland": "IRL",
    "isle of man": "IMN",
    "israel": "ISR",
    "italy": "ITA",
    "jamaica": "JAM",
    "japan": "JPN",
    "jersey": "JEY",
    "jordan": "JOR",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "kiribati": "KIR",
    "korea (democratic people's republic of)": "PRK",
    "korea (republic of)": "KOR",
    "kuwait": "KWT",
    "kyrgyzstan": "KGZ",
    "lao people's democratic republic": "LAO",
    "latvia": "LVA",
    "lebanon": "LBN",
    "lesotho": "LSO",
    "liberia": "LBR",
    "libya": "LBY",
    "liechtenstein": "LIE",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "macao": "MAC",
    "macedonia (the former yugoslav republic of)": "MKD",
    "madagascar": "MDG",
    "malawi": "MWI",
    "malaysia": "MYS",
    "maldives": "MDV",
    "mali": "MLI",
    "malta": "MLT",
    "marshall islands": "MHL",
    "martinique": "MTQ",
    "mauritania": "MRT",
    "mauritius": "MUS",
    "mayotte": "MYT",
    "mexico": "MEX",
    "micronesia (federated states of)": "FSM",
    "moldova (republic of)": "MDA",
    "monaco": "MCO",
    "mongolia": "MNG",
    "montenegro": "MNE",
    "montserrat": "MSR",
    "morocco": "MAR",
    "mozambique": "MOZ",
    "myanmar": "MMR",
    "namibia": "NAM",
    "nauru": "NRU",
    "nepal": "NPL",
    "netherlands": "NLD",
    "new caledonia": "NCL",
    "new zealand": "NZL",
    "nicaragua": "NIC",
    "niger": "NER",
    "nigeria": "NGA",
    "niue": "NIU",
    "norfolk island": "NFK",
    "northern mariana islands": "MNP",
    "norway": "NOR",
    "oman": "OMN",
    "pakistan": "PAK",
    "palau": "PLW",
    "palestine, state of": "PSE",
    "panama": "PAN",
    "papua new guinea": "PNG",
    "paraguay": "PRY",
    "peru": "PER",
    "philippines": "PHL",
    "pitcairn": "PCN",
    "poland": "POL",
    "portugal": "PRT",
    "puerto rico": "PRI",
    "qatar": "QAT",
    "rÃ©union": "REU",
    "romania": "ROU",
    "russian federation": "RUS",
    "rwanda": "RWA",
    "saint barthÃ©lemy": "BLM",
    "saint helena, ascension and tristan da cunha": "SHN",
    "saint kitts and nevis": "KNA",
    "saint lucia": "LCA",
    "saint martin (french part)": "MAF",
    "saint pierre and miquelon": "SPM",
    "saint vincent and the grenadines": "VCT",
    "samoa": "WSM",
    "san marino": "SMR",
    "sao tome and principe": "STP",
    "saudi arabia": "SAU",
    "senegal": "SEN",
    "serbia": "SRB",
    "seychelles": "SYC",
    "sierra leone": "SLE",
    "singapore": "SGP",
    "sint maarten (dutch part)": "SXM",
    "slovakia": "SVK",
    "slovenia": "SVN",
    "solomon islands": "SLB",
    "somalia": "SOM",
    "south africa": "ZAF",
    "south georgia and the south sandwich islands": "SGS",
    "south sudan": "SSD",
    "spain": "ESP",
    "sri lanka": "LKA",
    "sudan": "SDN",
    "suriname": "SUR",
    "svalbard and jan mayen": "SJM",
    "swaziland": "SWZ",
    "sweden": "SWE",
    "switzerland": "CHE",
    "syrian arab republic": "SYR",
    "taiwan, province of china": "TWN",
    "tajikistan": "TJK",
    "tanzania, united republic of": "TZA",
    "thailand": "THA",
    "timor-leste": "TLS",
    "togo": "TGO",
    "tokelau": "TKL",
    "tonga": "TON",
    "trinidad and tobago": "TTO",
    "tunisia": "TUN",
    "turkey": "TUR",
    "turkmenistan": "TKM",
    "turks and caicos islands": "TCA",
    "tuvalu": "TUV",
    "uganda": "UGA",
    "ukraine": "UKR",
    "united arab emirates": "ARE",
    "united kingdom of great britain and northern ireland": "GBR",
    "united states of america": "USA",
    "united states minor outlying islands": "UMI",
    "uruguay": "URY",
    "uzbekistan": "UZB",
    "vanuatu": "VUT",
    "venezuela (bolivarian republic of)": "VEN",
    "viet nam": "VNM",
    "virgin islands (british)": "VGB",
    "virgin islands (u.s.)": "VIR",
    "wallis and futuna": "WLF",
    "western sahara": "ESH",
    "yemen": "YEM",
    "zambia": "ZMB",
    "zimbabwe": "ZWE",
    "uk": "GBR",
    "russia": "RUS",
    "west germany": "DEU",
    "east germany": "DEU",
    "soviet union": "RUS",
    "hong kong": "CHN",
}

function getCountryISO(country) {
    country = country.toLowerCase();
    let code = countryCodes[country];
    if (code)
        return code;
    return country.toUpperCase();
}
